resolver: nightly-2022-06-08
extra-deps:
  - git: https://github.com/nikita-volkov/coalmine
    commit: 43e22a08f532e8279c784852ef0a213f7aeb1d37
  - git: https://github.com/nikita-volkov/moore-machines
    commit: 7e95c33b203a1cfe42dbc0e0de3cec8e6fe94290
  - git: https://github.com/nikita-volkov/structure-kit
    commit: 46ffb6527c48f8a718adecd21a313f0b1ba5e81c
  - git: https://github.com/nikita-volkov/lean-http-client
    commit: 52343895df1e5ae49159b8c5f76a50ac438216b1
  - git: https://github.com/nikita-volkov/distillery
    commit: 2c2905f2addb0d1925c43d427fcf65340ee64b2a
  - aeson-value-parser-0.19.7
  - cereal-unordered-containers-0.1
  - cereal-data-dword-0.1.1
  - domain-aeson-0.1
  - domain-cereal-0.1
  - punycode-2.0
  - timestamp-0.2
  - leb128-cereal-1.2
  - vector-extras-0.2.7
  - isomorphism-class-0.1.0.1
  - text-builder-dev-0.3.3
  - git: https://github.com/pgenie-io/protocol
    commit: 897af90cd2c0b32ed39b4240273d21333b5d0bfb
  - git: https://github.com/pgenie-io/client
    commit: 176a09c1b6ff2971d59d9c0e65f3471c8956f8b5
  - git: https://github.com/pgenie-io/config
    commit: 361a2b415c7c1a75b8235c7414e6a81326026faa
