
name: Release

on:
  push:
    branches:
      - dev

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.get-metadata.outputs.name }}
      version: ${{ steps.get-metadata.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: get-metadata
        uses: nikita-volkov/extract-metadata-from-cabal@v1.0.0

  build-linux-artifact:
    runs-on: ubuntu-latest
    needs:
      - get-metadata
    env:
      ARTIFACT: artifact/${{ needs.get-metadata.outputs.name }}-v${{ needs.get-metadata.outputs.version }}-linux-x64.tar.xz
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 2.7.5
          stack-no-global: true
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: ${{ runner.os }}-
      - run: stack build --local-bin-path artifact --copy-bins
      - run: tar cJvf "${{env.ARTIFACT}}" -C artifact pgn
      - uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: ${{env.ARTIFACT}}
          if-no-files-found: error

  build-macos-artifact:
    runs-on: macos-latest
    needs:
      - get-metadata
    env:
      ARTIFACT: artifact/${{ needs.get-metadata.outputs.name }}-v${{ needs.get-metadata.outputs.version }}-macos-x64.tar.xz
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 2.7.5
          stack-no-global: true
      - uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: ${{ runner.os }}-
      - run: stack build --local-bin-path artifact --copy-bins
      - run: tar cJvf "${{env.ARTIFACT}}" -C artifact pgn
      - uses: actions/upload-artifact@v3
        with:
          name: macos-x64
          path: ${{env.ARTIFACT}}
          if-no-files-found: error
  
  build-windows-artifact:
    runs-on: windows-latest
    needs:
      - get-metadata
    env:
      ARTIFACT: artifact/${{ needs.get-metadata.outputs.name }}-v${{ needs.get-metadata.outputs.version }}-windows-x64.tar.xz
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 2.7.5
          stack-no-global: true
      - uses: actions/cache@v3
        with:
          path: |
            C:\sr
            ~\AppData\Roaming\stack
            ~\AppData\Local\Programs\stack
            .stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: ${{ runner.os }}-
      - run: stack build --local-bin-path artifact --copy-bins
      - uses: thedoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: ${{env.ARTIFACT}}
          path: artifact/pgn.exe
      - uses: actions/upload-artifact@v3
        with:
          name: windows-x64
          path: ${{env.ARTIFACT}}
          if-no-files-found: error

  release:
    needs:
      - get-metadata
      - build-linux-artifact
      - build-macos-artifact
      - build-windows-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux-x64
          path: artifact
      - uses: actions/download-artifact@v2
        with:
          name: macos-x64
          path: artifact
      - uses: actions/download-artifact@v2
        with:
          name: windows-x64
          path: artifact
      - name: Tag and release
        uses: avakar/tag-and-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.get-metadata.outputs.version }}
      - name: Upload assets to Github release
        uses: xresloader/upload-to-github-release@v1.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "artifact/*"
          tag_name: v${{ needs.get-metadata.outputs.version }}
